# Site info
siteTitle: "Open Source Camp @Iași"

# About Block
aboutTitle: "About Open Source Camp"
aboutBlock:
  - title: "Conference"
    image: "conference.jpg"
    text: >
      The Open Source gathering of the year in Romania, built with care
      by geeks for enthusiasts. Awesome technical speakers and talks and
      of course, loads of fun!
  - title: "Workshops"
    image: "workshop.jpg"
    text: >
      Full-day of workshops and hands-on experience, hacking and debugging.
      Join us in an epic battle to unleash the power of your favorite new
      technology!

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Aula Magna Mihai Eminescu"
eventLocationLink: "https://www.uaic.ro/organizare/departamentul-de-marketing-educational-evenimente-si-imagine-academica/oportunitati-pentru-organizarea-evenimentelor/aula-magna-mihai-eminescu/"
eventStreetAddress: "Universitatea Alexandru Ioan Cuza din Iași, Bulevardul Carol I, Nr.11"
eventAddressLocality: "Iași"
eventAddressLocalityRegion: "Iași"
eventPostalCode: "700506"
eventAddressCountry: "Romania"
eventStartTime: "2016-05-07T09:00"
eventDoorTime: "08:00"
eventEndTime: "2016-05-08T18:00"
eventPlaceCoordinates: "47.174524,27.572306"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Aula Magna Mihai Eminescu"
venueFeatures:
  - 258 seats on the ground floor
  - 168 seats on balacony
  - Digital Surround audio system
  - Located in the university campus

# Team Block
teamBlockTitle: "About us"
aboutUs: >
    Finally, the step we've been waiting for has been taken by a large
    amount of tech industry giants and important figures. From the beginning
    of the IT industry, the Open Source trend has been an element of geek legends,
    but the myth becomes reality in a push of the industry towards greater grounds.
    In our enthusiasm, we want to share the beautiful things this old taboo subject has
    to offer in the software industry, with the help, of course, of great minds with
    state of the art skills. So we hope you'll give us the chance to impress in our
    Open Source Camp hosted in Iași, Romania. Join us for tech talks, workshops and
    an awesome hackathon that will keep you up in excitement.

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - count: "300"
   specialCharacter: "+"
   info: "attendees"
   detail: "from everywhere"

 - count: "72"
   specialCharacter: "+"
   info: "hours"
   detail: "of pure open source technologies"

 - count: "15"
   specialCharacter: "+"
   info: "speakers"
   detail: "from country and beyond"

# Rockstar Speakers Block
rockstar:
    title: "Meet our awesome speakers"
    background: "rockstar-speakers.jpg"
    speakers_count: 6
    speakers_url: "/2016/speakers/"

# Documents
c4pUrl: "https://oscamp.eu/blog/call-for-proposals-2016"

footerBlocks:
 - title: "Contact"
   links:
      - {link: "mailto:contact@oscamp.eu", text: "contact@oscamp.eu"}

 - title: "FAQ"
   links:
      - {permalink: "/cod/", text: "Code of Conduct"}

 - title: "Previous edition"
   links:
      - {link: "https://opensourceiasi.wordpress.com/", text: "Open Source Iași"}
